server:
  port: 99
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:hsql://localhost/testdb
    username: sa
    password:
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework: TRACE
    com:
      example: INFO
environment:
  profiles: dev
  name: Developer App
  url: http://localhost