CREATE TABLE IF NOT EXISTS posts(
    id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS comments(
    id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    text TEXT NOT NULL,
    post_id BIGINT(20),
    FOREIGN KEY (post_id) REFERENCES posts(id)
)
